name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3

      - name: Node.js installieren
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Abhängigkeiten installieren
        run: npm install

      - name: Tests ausführen
        run: npm test

      - name: Build erzeugen
        run: npm run build
